blog/urls.py
from django.urls import path
from blog.views.user_authentication import user_registration, user_login, user_logout
from blog.views.post_views import post_list, post_details, post_search, pending_posts, approve_post, create_post, pending_comments, approve_comments, hide_comments, post_like
from blog.views.index_view import home_view




# app_name = 'blog'

urlpatterns = [
    path('', home_view, name='home'),

    path('register/', user_registration, name='user_registration'),
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),

    path('blog/', post_list, name='post_list'),
    path('blog/pending-posts/', pending_posts, name='pending_posts'),
    path('blog/approve-post/<int:post_id>/', approve_post, name='approve_post'),
    path('blog/pending-comments/', pending_comments, name='pending_comments'),
    path('blog/approve-comments/<int:comment_id>/', approve_comments, name='approve_comments'),
    path('blog/hide-comments/<int:comment_id>/', hide_comments, name='hide_comments'),
    path('blog/search/', post_search, name='post_search'),
    path('blog/create_post/', create_post, name='create_post'),
    path('blog/<slug:post_slug>/', post_details, name='post_details'),
    path('blog/<slug:post_slug>/like/', post_like, name='post_like'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('tag/', include('tag.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tag/urls.py
from django.urls import path
from tag.views import tag_view, create_tag

app_name = 'tag'

urlpatterns = [
    path('create_tag/', create_tag, name='create_tag'),
    path('<slug:tag_slug>/', tag_view, name='tag_view'),
    
]

blog/models/comment.py
from django.db import models
from base.models import BaseModel
from blog.models import User, Post


class CommentQuerySet(models.QuerySet):
    def show_approved(self):
        return self.filter(is_shown = True)
    
    def approve(self):
        return self.update(is_shown = True)
    
    def hide(self):
        return self.update(is_shown = False)


class Comment(BaseModel):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    is_shown = models.BooleanField(default=False)

    objects = CommentQuerySet.as_manager()
    class Meta:
        permissions = [
            ("approve_comment", "Can approve comment"),
            ("hide_comment", "Can hide comment"),
        ]

    def approve_comment(self):
        self.is_shown = True
        self.save()

    def hide_comment(self):
        self.is_shown = False
        self.save()

    def __str__(self):
        return f"{self.user.username} on {self.post.title}"

blog/models/like.py
from django.db import models
from blog.models.user import User
from blog.models.post import Post
from base.models import BaseModel


class Like(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f"{self.user.username} liked {self.post.title}"

blog/models/post.py
from django.db import models
from django.utils.text import slugify

from base.models import BaseModel
from blog.models import User
from tag.models import Tag


class Post(BaseModel):
    POST_STATUS_PENDING = "P"
    POST_STATUS_CONFIRMED = "C"
    POST_STATUS_REFUSED = "R"
    POST_STATUS_HIDDEN = "H"
    POST_STATUS_CHOICES = [
        (POST_STATUS_PENDING, "Pending"),
        (POST_STATUS_CONFIRMED, "Confirmed"),
        (POST_STATUS_REFUSED, "Refused"),
        (POST_STATUS_HIDDEN, "Hidden"),
    ]
    author = models.ForeignKey(to=User, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=255, unique=True)
    image = models.ImageField(upload_to="blog_photoes/", null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    content = models.TextField()
    status = models.CharField(
        max_length=1, choices=POST_STATUS_CHOICES, default=POST_STATUS_PENDING
    )
    tag = models.ManyToManyField(Tag)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    like_count = models.IntegerField(default=0)
    visit_count = models.IntegerField(default=0)
    published_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        permissions = [
            ("approve_post", "Can approve post"),
        ]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.title} by {self.author.username}"

blog/models/user.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from base.models import BaseModel


class User(AbstractUser, BaseModel):
    USER_ADMIN = "A"
    USER_VIEWER = "V"
    USER_WRITER = "W"

    USER_ROLE_CHOICES = [
        (USER_ADMIN, "admin"),
        (USER_VIEWER, "viewer"),
        (USER_WRITER, "writer"),
    ]
    phone = models.CharField(max_length=15, unique=True, null=True, blank=True)
    user_role = models.CharField(
        max_length=1, choices=USER_ROLE_CHOICES, default=USER_VIEWER
    )

    class Meta:
        permissions = [
            ("view_user_list", "Can view user list"),
            ("edit_user", "Can edit user"),
        ]
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

blog/forms/blog_post_form.py
from django import forms
from blog.models.post import Post
from tag.models import Tag



class BlogPostForm(forms.ModelForm):
    tag = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'tag']

blog/forms/comments_form.py
from django import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

blog/forms/login_form.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput())

blog/forms/register_form.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from blog.models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    phone = forms.CharField(max_length=15, required=False)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'phone',
            'password1',
            'password2',
        ]

blog/views/index_view.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'home/home_page.html')

blog/views/post_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib import messages

from blog.forms.blog_post_form import BlogPostForm
from blog.forms.comments_form import CommentForm
from blog.models.comment import Comment
from blog.models.post import Post



@login_required
def create_post(request):
    if request.user.user_role not in ['W', 'A']:
        messages.error(request, "You cannot create a blogpost since you are not a writer or an admin")
        return redirect('home')
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            form.save_m2m()

            # To keep the last five posts created by the user in session
            recent_user_posts = request.session.get('recent_user_posts', [])
            recent_user_posts.insert(0, new_post.id)
            request.session['recent_user_posts'] = recent_user_posts[:5]
            request.session.modified = True

            return redirect('post_details', post_slug=new_post.slug)
    else:
        form = BlogPostForm()

    return render(request, 'blog/blog_post.html', {'form': form})


@permission_required('blog.approve_post')
def approve_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.status = Post.POST_STATUS_CONFIRMED
    post.save()
    return redirect('post_list')


@permission_required('blog.approve_comment')
def approve_comments(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.approve_comment()
    return redirect('pending_comments')


@permission_required('blog.hide_comment')
def hide_comments(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.hide_comment()
    return redirect('pending_comments')


@login_required
def pending_posts(request):
    if request.user.user_role not in ['W', 'A']:
        messages.error(request, "You cannot access this url since you are not a writer or an admin")
        return redirect('home')
    posts = Post.objects.filter(status="P")
    context = {"posts": posts}
    return render(request, "blog/pending_posts.html", context)


@login_required
def pending_comments(request):
    if request.user.user_role not in ['W', 'A']:
        messages.error(request, "You cannot access this url since you are not a writer or an admin")
        return redirect('home')
    hidden_comments = Comment.objects.filter(is_shown=False).order_by('-created_at')
    approved_comments = Comment.objects.filter(is_shown=False).order_by('-created_at')
    context = {
        "approved_comments": approved_comments,
        "hidden_comments": hidden_comments,
        }
    return render(request, "blog/pending_comments.html", context)


@login_required
def post_details(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    user = request.user

    # Increment visit count
    post.visit_count += 1
    post.save()

    # Update session history
    recent_posts = request.session.get('history', [])
    if post_slug not in recent_posts:
        recent_posts.append(post_slug)
    recent = recent_posts[:5]
    request.session['history'] = recent

    # Handle comment form
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = user
            comment.save()
            messages.success(request, 'Comment added successfully')
            return redirect('post_details', post_slug=post_slug)
        else:
            messages.error(request, 'Invalid comment')
            return redirect('post_details', post_slug=post_slug)
    else:
        form = CommentForm()

    # return tags of the post
    tags = post.tag.all()
    tag_names = []
    for tag in tags:
        tag_names.append(tag)

    comments = Comment.objects.filter(post=post).order_by('-created_at').show_approved()
    context = {"post": post, "comments": comments, "form": form, "tag_names": tag_names}
    response = render(request, 'blog/post_details.html', context)
    response.set_cookie('last_viewed_post', post_slug, max_age=60*60*24*5)
    return response


@login_required
def post_list(request):
    posts = Post.objects.filter(status="C").order_by('-created_at')
    paginator = Paginator(posts, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, 'blog/post_list.html', context)


@login_required
def post_search(request):
    posts = Post.objects.filter(status="C")
    if request.method == 'GET':
        search_query = request.GET.get("q")
        if search_query:
            posts = posts.filter(
                Q(content__icontains=search_query) |
                Q(title__icontains=search_query)
            )
    paginator = Paginator(posts, 4)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    context = {"page_obj": page_obj, "search_query": search_query}
    return render(request, ("blog/post_list.html"), context)


@login_required
def post_like(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    user = request.user
    if user in post.likes.all():  
        post.likes.remove(user)
        post.like_count -= 1
        messages.success(request, 'Post unliked successfully')
    else:
        post.likes.add(user)
        post.like_count += 1
        messages.success(request, 'Post liked successfully')
    post.save()
    return redirect('post_details', post_slug=post_slug)

blog/views/user_authentication.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from blog.forms import LoginForm, RegistrationForm
from django.contrib.auth.decorators import permission_required
from blog.models import User


def user_registration(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')

            if User.objects.filter(email=email).exists():
                messages.error(request, "Email already exists.")
                return render(request, 'registration/register.html', {"form": form})
            if User.objects.filter(username=username).exists():
                messages.error(request, "Username already exists.")
                return render(request, 'registration/register.html', {"form": form})

            form.save()
            messages.success(request, "Registration successful! You can now log in.")
            return redirect('user_login')
        else:
            messages.error(request, "Please correct the errors below.")
            return render(request, 'registration/register.html', {"form": form})
        
    form = RegistrationForm()
    return render(request, 'registration/register.html', {"form": form})


def user_login(request):
    if request.user.is_authenticated:
        return redirect('home')

    form = LoginForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, 'Logged in successfully!')
                return redirect('home')
            else:
                messages.error(request, "Invalid username or password.")

    return render(request, 'registration/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('home')

blog/templates/blog/blog_post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}create post{% endblock %}

{% block content %}
    <div style="display: flex; gap: 10px;">
        <a href="{% url 'tag:create_tag' %}">
          <button class="create-post-button" type="submit">Create a New tag</button>
        </a>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Done</button>
    </form>
{% endblock %}

blog/templates/blog/last_viewed_post.html
<!-- last_viewed_post.html -->

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'blog/style_last_viewed_post.css' %}">
{% endblock %}

{% if last_viewed_post %}
<div class="last-viewed-post">
    <h2>Last Viewed Post</h2>
    <a href="{% url 'post_details' last_viewed_post.slug %}">
    <div class="last-viewed-post-content">
        {% if last_viewed_post.image %}
            <img src="{{ last_viewed_post.image.url }}" alt="{{ last_viewed_post.title }}">
        {% else %}
            <img src="{% static 'img/default.jpg' %}" alt="Default Image">
        {% endif %}
        <div class="last-viewed-post-info">
            <h3>{{ last_viewed_post.title }}</h3>
            <p>by {{ last_viewed_post.author.username }}</p>
        </div>
    </div>
    </a>
</div>
{% endif %}

blog/templates/blog/pending_comments.html
{% extends 'base.html' %}

{% block content %}
<h1>Pending comments</h1>
<br>
<h2> Approved Comments </h2>
----------------------------------
{% for comment in approved_comments %}
    <h4>{{ comment.user.username }}</h4>
    <p>{{ comment.post.title }}</p>
    <p>{{ comment.text }}</p>
    <p>comment is shown: {{ comment.is_shown }}</p>
    <a href="{% url 'hide_comments' comment.id %}"><button>hide</button></a>
{% empty %}
    <p>No approved comments found.</p>    
{% endfor %}
<br>
<br>
<h2> Hidden Comments </h2>
----------------------------------
{% for comment in hidden_comments %}
    <h4>{{ comment.user.username }}</h4>
    <p>{{ comment.post.title }}</p>
    <p>{{ comment.text }}</p>
    <p>comment is shown: {{ comment.is_shown }}</p>
    <a href="{% url 'approve_comments' comment.id %}"><button>Approve</button></a>
{% empty %}
    <p>No hidden comments found.</p>
{% endfor %}
{% endblock %} 

blog/templates/blog/pending_posts.html
{% extends 'base.html' %}

{% block content %}
<h1>Pending Posts</h1>
{% for post in posts %}
    <h2>{{ post.title }}</h2>
    <p>{{ post.content }}</p>
    <p>{{ post.author }}</p>
    <a href="{% url 'approve_post' post.id %}"><button>Approve</button></a>
{% endfor %}
{% endblock %}

blog/templates/blog/post_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ post.title }} - Blog Post
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'blog/style_post_details.css' %}">
{% endblock %}
{% block content %}

<div class="post-details-card">
    {% if messages %}
        <div class="messages-container">
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="post-header">
        <h1>{{ post.title }}</h1>
        <div class="post-meta">
            <span>By <strong>{{ post.author }}</strong></span>
            <span class="dot">•</span>
            <span>{{ post.published_date|date:"F j, Y" }}</span>
        </div>
    </div>
    <div class="tags-container" style="display:flex; gap:10px; flex-wrap:wrap;">
        {% for tag in tag_names %}
            <a href="{% url 'tag:tag_view' tag.slug %}">{{ tag.name }}</a>
        {% endfor %}
    </div>
    <div class="post-image-container">
        {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.title }}">
        {% else %}
            <img src="{% static 'img/default.jpg' %}" alt="Default image">
        {% endif %}
    </div>

    <div class="post-content">
        <p>{{ post.content }}</p>
    </div>

    <div class="post-stats">
        <form method="post" action="{% url 'post_like' post.slug %}" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="like-button {% if request.user in post.likes.all %}liked{% endif %}">
                {% if request.user in post.likes.all %}
                    ❤️ {{ post.like_count }} Likes
                {% else %}
                    🤍 {{ post.like_count }} Likes
                {% endif %}
            </button>
        </form>
        <span>👁️ {{ post.visit_count }} Views</span>
    </div>
    <div class="comments-section">
        <h3>Comments</h3>
        <div class="comments-list">
            {% if comments %}
                {% for comment in comments %}
                <div class="card" style="background:rgba(236,245,255,0.7); margin-bottom:18px; animation:fadeIn 0.7s;">
                    <div style="display:flex; align-items:center; gap:12px;">
                        <img src="{% static 'img/profile_defualt.jpg' %}" style="width:36px; height:36px; border-radius:50%; object-fit:cover;">
                        <div>
                            <span style="font-weight:700; color:var(--primary-dark);">@{{ comment.user.username }}</span>
                            <span style="color:#888; font-size:0.95em;">{{ comment.created_at|date:"F j, Y" }}</span>
                        </div>
                    </div>
                    <div style="margin-top:10px; color:#333;">{{ comment.text }}</div>
                </div>
                {% endfor %}
            {% else %}
                <p class="no-comments">No comments yet. Be the first!</p>
            {% endif %}
        </div>

        <h3>Leave a Comment</h3>
        <form method="post" class="comment-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Post Comment</button>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Blog Page{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'blog/style_post_list.css' %}">
{% endblock %}
{% block content %}   
    <div style="display: flex; gap: 10px;">

        {% if request.user.user_role == 'W' or request.user.user_role == 'A' %}
        <a href="{% url 'create_post' %}">
          <button class="create-post-button" type="submit">Create a New Post</button>
        </a>
        <a href="{% url 'pending_comments' %}">
          <button class="create-post-button" type="submit">Pending Comments</button>
        </a>
        <a href="{% url 'pending_posts' %}">
          <button class="create-post-button" type="submit">Pending Posts</button>
        </a>
        {% endif %}

      </div>
    <h2>

    {% if search_query %}
        Results for "{{ search_query }}"
    {% elif tag_name %}
        All Posts of "{{ tag_name }}" tag
    {% else %}
        All Posts
    {% endif %}
    
</h2>
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 36px;">
    {% for post in page_obj %}
    <div class="card" style="padding:0; overflow:hidden;">
        <a href="{% url 'post_details' post.slug %}">
            {% if post.image %}
                <img src="{{post.image.url}}" style="width:100%; height:180px; object-fit:cover; transition:transform 0.3s;">
            {% else %}
                <img src="{% static 'img/default.jpg' %}" style="width:100%; height:180px; object-fit:cover;">
            {% endif %}
        </a>
        <div style="padding: 20px 22px;">
            <h3 style="margin:0 0 8px 0;">{{ post.title }}</h3>
            <div style="display:flex; align-items:center; gap:10px; color:#888; font-size:0.98em;">
                <img src="{% static 'img/profile_defualt.jpg' %}" style="width:28px; height:28px; border-radius:50%; object-fit:cover;">
                <span>By {{ post.author }}</span>
            </div>
            <p style="margin: 14px 0 0 0; color:#444;">{{ post.content|truncatewords:30 }}</p>
            <a href="{% url 'post_details' post.slug %}" class="btn" style="margin-top: 18px; display:inline-block;">Show More</a>
        </div>
    </div>
    {% endfor %}
</div>
<div class="pagination" style="margin-top: 40px; text-align: center;">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="btn">Previous</a>
    {% endif %}
    <span style="margin: 0 16px;">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn">Next</a>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/recent_post.html
{% load static %}
{% block content %}
    {% if recent_posts %}
            <h2>Viewed History</h2>
            
            {% for post in recent_posts %}
                <div>
                    <h4>{{ post.title }}</h4>
                    {% if post.image %}
                    <img src="{{post.image.url}}" width="200px">
                    {% else %}
                    <img src="{% static 'img/default.jpg' %}" width="200px">
                    {% endif %}
                    <p>by: {{ post.author.username }}</p>
                    <a href="{% url 'post_details' post.slug %}" class="btn">
                        <button>Show More</button>
                    </a>
                </div>
            {% endfor %}
    {% else %}
        <p>No recent posts</p>
    {% endif %}
    {% endblock %}

blog/templates/blog/search_bar.html
{% load static %}

<form method="GET" action="{% url 'post_search' %}" class="search-form" style="margin-bottom: 24px;">
    <input type="text" name="q" placeholder="Search posts..." class="search-input">
    <button type="submit" class="search-button">&#128269;</button>
</form>